name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
    env:
      SONAR_TOKEN: ${{ secrets.BACK_SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.BACK_SONAR_HOST_URL }}
