name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: SonarQube Scan
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=BACK_PROJECT_KEY \
          -Dsonar.host.url=BACK_SONARQUBE_URL \
          -Dsonar.login=BACK_SONARQUBE_TOKEN
